// Player ID to Name mapping for odds API
// This maps database player IDs to the names expected by the odds API

export const PLAYER_ID_TO_NAME: { [key: string]: string } = {
  // All 150 players from database
  176: "Aaliyah Edwards",
  128: "Aaliyah Nye",
  54: "Aari McDonald",
  130: "A'ja Wilson",
  184: "Alanna Smith",
  56: "Aliyah Boston",
  140: "Allisha Gray",
  84: "Alysha Clark",
  201: "Alyssa Thomas",
  183: "Anastasiia Olairi Kosu",
  120: "Aneesah Morrow",
  159: "Angel Reese",
  160: "Ariel Atkins",
  107: "Arike Ogunbowale",
  101: "Aziaha James",
  153: "Azurá Stevens",
  73: "Breanna Stewart",
  117: "Bria Hartley",
  59: "Brianna Turner",
  182: "Bridget Carleton",
  141: "Brionna Jones",
  144: "Brittney Griner",
  173: "Brittney Sykes",
  62: "Caitlin Clark",
  152: "Cameron Brink",
  87: "Carla Leite",
  97: "Cecilia Zandalasini",
  127: "Chelsea Gray",
  132: "Cheyenne Parker-Tyus",
  166: "Courtney Vandersloot",
  185: "Courtney Williams",
  60: "Damiris Dantas",
  126: "Dana Evans",
  147: "Dearica Hamby",
  197: "DeWanna Bonner",
  180: "Diamond Miller",
  106: "DiJonai Carrington",
  81: "Dominique Malonga",
  156: "Elizabeth Williams",
  174: "Emily Engstler",
  154: "Emma Cannon",
  82: "Erica Wheeler",
  80: "Ezi Magbegor",
  77: "Gabby Williams",
  172: "Georgia Amoore",
  110: "Grace Berger",
  157: "Hailey Van Lith",
  109: "Haley Jones",
  114: "Haley Peters",
  91: "Iliana Rupert",
  70: "Isabelle Harrison",
  123: "Jackie Young",
  113: "Jacy Sheldon",
  171: "Jade Melbourne",
  92: "Janelle Salaün",
  64: "Jaylyn Sherrod",
  186: "Jessica Shepard",
  131: "Jewell Loyd",
  102: "JJ Quinerly",
  74: "Jonquel Jones",
  136: "Jordin Canada",
  151: "Julie Allemand",
  155: "Julie Vanloo",
  193: "Kahleah Copper",
  88: "Kaitlyn Chen",
  198: "Kalani Brown",
  162: "Kamilla Cardoso",
  189: "Karlie Samuelson",
  95: "Kate Martin",
  200: "Kathryn Westbeld",
  85: "Katie Lou Samuelson",
  187: "Kayla McBride",
  90: "Kayla Thornton",
  53: "Kelsey Mitchell",
  148: "Kelsey Plum",
  71: "Kennedy Burke",
  133: "Kiah Stokes",
  199: "Kiana Williams",
  163: "Kia Nurse",
  124: "Kierstan Bell",
  179: "Kiki Iriafen",
  196: "Kitija Laksa",
  89: "Laeticia Amihere",
  122: "Leïla Lacan",
  68: "Leonie Fiebich",
  79: "Lexie Brown",
  58: "Lexie Hull",
  192: "Lexi Held",
  118: "Lindsay Allen",
  108: "Li Yueru",
  178: "Lucy Olsen",
  104: "Luisa Geiselsöder",
  86: "Mackenzie Holmes",
  105: "Maddy Siegrist",
  165: "Maddy Westbeld",
  61: "Makayla Timpson",
  190: "Maria Kliundikova",
  112: "Marina Mabrey",
  72: "Marine Johannès",
  143: "Maya Caldwell",
  129: "Megan Gustafson",
  164: "Michaela Onyenwere",
  195: "Monique Akoa Makani",
  98: "Monique Billings",
  158: "Moriah Jefferson",
  99: "Myisha Hines-Allen",
  125: "NaLyssa Smith",
  188: "Napheesa Collier",
  67: "Natasha Cloud",
  55: "Natasha Howard",
  194: "Natasha Mack",
  181: "Natisha Hiedeman",
  134: "Naz Hillmon",
  139: "Nia Coffey",
  75: "Nneka Ogwumike",
  66: "Nyara Sabally",
  115: "Olivia Nelson-Ododa",
  100: "Paige Bueckers",
  167: "Rachel Banham",
  149: "Rae Burrell",
  116: "Rayah Marshall",
  161: "Rebecca Allen",
  65: "Rebekah Gardner",
  138: "Rhyne Howard",
  146: "Rickea Jackson",
  69: "Sabrina Ionescu",
  202: "Sami Whitcomb",
  145: "Sania Feagin",
  119: "Saniya Rivers",
  150: "Sarah Ashlee Barker",
  191: "Satou Sabally",
  168: "Shakira Austin",
  142: "Shatori Walker-Kimbrough",
  170: "Sika Koné",
  76: "Skylar Diggins",
  175: "Sonia Citron",
  57: "Sophie Cunningham",
  177: "Stefanie Dolson",
  169: "Sug Sutton",
  63: "Sydney Colson",
  137: "Taylor Thierry",
  103: "Teaira McCowan",
  135: "Te-Hina Paopao",
  93: "Temi Fágbénlé",
  94: "Tiffany Hayes",
  83: "Tiffany Mitchell",
  121: "Tina Charles",
  111: "Tyasha Harris",
  96: "Veronica Burton",
  78: "Zia Cooke",
};

// Reverse mapping for convenience
export const PLAYER_NAME_TO_ID: { [key: string]: string } = Object.fromEntries(
  Object.entries(PLAYER_ID_TO_NAME).map(([id, name]) => [name, id])
);

export function getPlayerName(playerId: string): string {
  return PLAYER_ID_TO_NAME[playerId] || `Player ${playerId}`;
}

export function getPlayerId(playerName: string): string | null {
  return PLAYER_NAME_TO_ID[playerName] || null;
} 